# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-04 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20170503_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='taskpriority',
            options={'verbose_name_plural': 'Task Priorities'},
        ),
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name_plural': 'User Categories'},
        ),
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(null=True, to='Project.Task'),
        ),
    ]
