# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-04 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20170504_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='Project.Task'),
        ),
    ]
