# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-04 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_auto_20170504_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.Profile'),
        ),
    ]
